#!/usr/bin/env python3
"""
Build a single Quantumult X rewrite bundle from only the enabled app modules.

Security:
- No network access.
- No third-party runtime script URLs are allowed.
- Only raw.githubusercontent.com/meteoritesama/QuanX-Safe-AdBlock/... is allowed for script-* rules.
- Hostnames are de-duplicated into one final `hostname =` line.
"""
from pathlib import Path
import re
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
MODULES = ROOT / "modules"
ENABLED = ROOT / "config" / "enabled_apps.txt"
OUTPUT = ROOT / "rewrite" / "AdBlock.conf"
MANIFEST = ROOT / "rewrite" / "active-manifest.json"
CATALOG = ROOT / "catalog.json"

OWN_SCRIPT_PREFIX = "https://raw.githubusercontent.com/meteoritesama/QuanX-Safe-AdBlock/"
ALLOWED_SIMPLE = {"reject", "reject-200", "reject-dict", "reject-array", "reject-img"}

def load_enabled():
    result = []
    for raw in ENABLED.read_text(encoding="utf-8").splitlines():
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        if s not in result:
            result.append(s)
    return result


def sync_enabled_catalog(enabled):
    """Rewrite enabled_apps.txt canonically and auto-list all available/optional modules."""
    available = sorted(p.stem for p in MODULES.glob("*.conf"))
    optional = [key for key in available if key not in enabled]

    try:
        catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    except Exception:
        catalog = {}

    def label(key):
        item = catalog.get(key, {}) if isinstance(catalog, dict) else {}
        title = item.get("title") if isinstance(item, dict) else None
        return f"{key}  # {title}" if title else key

    lines = [
        "# QuanX Safe AdBlock - app module selector",
        "# Non-comment lines are ENABLED modules.",
        "# To enable an optional module, remove the leading '# ' from its line and run tools/build.py.",
        "# This file's catalog sections are regenerated automatically by tools/build.py.",
        "",
        "# Enabled modules",
    ]
    lines.extend(enabled)
    lines += [
        "",
        f"# All available modules ({len(available)}):",
    ]
    lines.extend(f"# {label(key)}" for key in available)
    lines += [
        "",
        f"# Optional modules available but NOT enabled ({len(optional)}):",
    ]
    lines.extend(f"# {label(key)}" for key in optional)
    lines.append("")
    ENABLED.write_text("\n".join(lines), encoding="utf-8")

def validate_rule(rule, module):
    pattern, action = rule.split(" url ", 1)
    try:
        re.compile(pattern)
    except re.error as e:
        raise SystemExit(f"{module}: invalid regex: {e}: {pattern}")

    action = action.strip()
    if action in ALLOWED_SIMPLE:
        return
    if action.startswith("302 "):
        return
    if action.startswith("script-"):
        urls = re.findall(r"https?://\S+", action)
        if not urls:
            raise SystemExit(f"{module}: script rule has no URL: {rule}")
        for url in urls:
            if not url.startswith(OWN_SCRIPT_PREFIX):
                raise SystemExit(f"{module}: third-party runtime script blocked: {url}")
        return
    raise SystemExit(f"{module}: unsupported action: {action}")

def main():
    enabled = load_enabled()
    rules = []
    hosts = []
    seen_rules = set()
    seen_hosts = set()
    summary = []

    for key in enabled:
        path = MODULES / f"{key}.conf"
        if not path.exists():
            raise SystemExit(f"Unknown module '{key}': {path} not found")

        module_rules = 0
        module_hosts = 0
        for raw in path.read_text(encoding="utf-8").splitlines():
            s = raw.strip()
            if not s or s.startswith("#"):
                continue
            if s.startswith("hostname ="):
                values = [x.strip() for x in s[len("hostname ="):].split(",") if x.strip()]
                for host in values:
                    if host not in seen_hosts:
                        seen_hosts.add(host)
                        hosts.append(host)
                        module_hosts += 1
                continue
            if " url " in s:
                validate_rule(s, key)
                if s not in seen_rules:
                    seen_rules.add(s)
                    rules.append((key, s))
                    module_rules += 1
                continue
            raise SystemExit(f"{key}: unsupported non-comment line: {s}")

        summary.append({"module": key, "rules_added": module_rules, "hosts_added": module_hosts})

    lines = [
        "# QuanX Safe AdBlock - GENERATED ACTIVE BUNDLE",
        "# DO NOT EDIT THIS FILE DIRECTLY.",
        "# Edit config/enabled_apps.txt or modules/*.conf, then run tools/build.py.",
        "# Runtime remote scripts are restricted to this repository only.",
        "",
    ]

    current = None
    for key, rule in rules:
        if key != current:
            if current is not None:
                lines.append("")
            lines.append(f"# --- {key} ---")
            current = key
        lines.append(rule)

    lines += [
        "",
        "# Consolidated MITM hostnames for enabled modules only.",
        "hostname = " + ", ".join(hosts),
        "",
    ]

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    manifest = {
        "enabled_modules": enabled,
        "rule_count": len(rules),
        "hostname_count": len(hosts),
        "modules": summary,
    }
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    sync_enabled_catalog(enabled)

    print(f"Built {OUTPUT}")
    print(f"Enabled modules: {len(enabled)}")
    print(f"Rewrite rules: {len(rules)}")
    print(f"MITM hostnames: {len(hosts)}")

if __name__ == "__main__":
    main()
