# Module: dianping
# App: 大众点评 / Dianping
# Mode: native

^https:\/\/img\.meituan\.net\/dpmobile\/.+93241\.png url reject-img
^https?:\/\/img\.meituan\.net\/dpmobile\/\w+\.(gif|jpg|jpg\.webp)$ url reject

hostname = img.meituan.net
