# Module: douyu
# App: 斗鱼直播 / Douyu
# Mode: native

^https?:\/\/daoyu\.sdo\.com\/api\/userCommon\/getAppStartAd url reject
^https?:\/\/staticlive\.douyucdn\.cn\/.+\/getStartSend url reject
^https?:\/\/rtbapi\.douyucdn\.cn\/japi\/sign\/app\/getinfo url reject
^https?:\/\/capi\.douyucdn\.cn\/lapi\/sign\/app(api)?\/getinfo\?client_sys=ios url reject

hostname = daoyu.sdo.com, staticlive.douyucdn.cn, rtbapi.douyucdn.cn, capi.douyucdn.cn
