# Module: meituan
# App: 美团 / Meituan
# Mode: native

^https?:\/\/wmapi\.meituan\.com\/api\/v\d+\/(openscreen\?ad|startpicture) url reject-200
^https?:\/\/(s3plus|flowplus)\.meituan\.net\/v\d\/\w+\/linglong\/\w+\.(gif|jpg|mp4) url reject

hostname = wmapi.meituan.com, s3plus.meituan.net, flowplus.meituan.net
