# Module: migu-video
# App: 咪咕视频 / Migu Video
# Mode: native

^https?:\/\/app\.c\.nf\.migu\.cn\/.*column\/start(-)?up-pic url reject-200
^https?:\/\/ad\.mcloud\.139\.com\/advertapi url reject-200
^https?:\/\/aikanvod\.miguvideo\.com\/video\/p\/i_adverseInterface\.jsp url reject-200
^https?:\/\/public-deliver9\.miguvideo\.com\/deliver\/site\/batchMatch\/mergeSpot\/miguvideo\/ url reject-dict
^https?:\/\/recommend-dy\.miguvideo\.com\/recommend-dynamic\/dataSource\/v1\/recommend\/merge url reject-dict
^https?:\/\/ggc\.miguvideo\.com\/v1\/iflyad\/deliverysystem\/direct\/ url reject
^https?:\/\/ggic\d+\.miguvideo\.com\/ad\/ url reject
^https?:\/\/ggx.+\.miguvideo\.com\/request\/sdk.+[^?]*$ url reject

hostname = app.c.nf.migu.cn, ad.mcloud.139.com, aikanvod.miguvideo.com, public-deliver9.miguvideo.com, recommend-dy.miguvideo.com, ggc.miguvideo.com, ggic*.miguvideo.com, ggx*.miguvideo.com
