# Module: tencent-video
# App: 腾讯视频 / Tencent Video
# Mode: native

^https?:\/\/vv\.video\.qq\.com\/getvmind\? url reject
(?i)\bvmind\.qqvideo\.tc\.qq\.com\/[\w\/\.-]+[a-z]\d+\.mp4\? url reject
^https?:\/\/video\.dispatch\.tc\.qq\.com\/\w+\.p20\d\.1\.mp4 url reject

hostname = vv.video.qq.com, bvmind.qqvideo.tc.qq.com, video.dispatch.tc.qq.com
