# Module: tieba
# App: 百度贴吧 / Baidu Tieba
# Mode: native

^https?:\/\/c\.tieba\.baidu\.com\/c\/f\/forum\/getAdInfo url reject
^https?:\/\/c\.tieba\.baidu\.com\/c\/s\/splashSchedule url reject

hostname = c.tieba.baidu.com
