# Module: xiaohongshu
# App: 小红书 / Xiaohongshu
# Mode: native

^https?:\/\/www\.xiaohongshu\.com\/api\/sns\/v\d\/ads\/ url reject-dict
^https?:\/\/www\.xiaohongshu\.com\/api\/sns\/v\d\/system_service\/splash_config url reject
^https?:\/\/ads-img-al\.xhscdn\.com\/hera\/ url reject

hostname = www.xiaohongshu.com, ads-img-al.xhscdn.com
