# Module: zhihu
# App: 知乎 / Zhihu
# Mode: native

^https:\/\/api\.zhihu\.com\/commercial_api\/(banners_v3\/app_topstory_banner|launch_v2|real_time_launch_v2) url reject-dict
^https:\/\/api\.zhihu\.com\/ad-style-service\/request url reject-dict

hostname = api.zhihu.com
